# Generated by Django 5.0.1 on 2024-03-21 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduprod', '0002_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
