# Generated by Django 5.0.1 on 2024-04-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprod', '0004_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(default='multipleChoice', max_length=50),
        ),
    ]
